Closes #37
thinknetica-django-lab-04/UNCLT pull request #73
Opened 2021-09-02 22:27 UTC by UNCLT

Closes #37

2021-09-06 10:06 UTC, morgangt requested changes

2021-09-06 10:06 UTC, morgangt commented on myAvito/main/tests.py
> +#      Category.objects.get(title='cars'),
зачем комментировать тест?

2021-09-06 10:06 UTC, morgangt commented on myAvito/main/tests.py
> +    # ['TestUser3', 'testpass3', 'testmail3@test.com', '333333333333'],
либо удалить либо раздокуменътировать

2021-09-06 10:06 UTC, morgangt commented on myAvito/main/models.py
> +        instance.groups.add(Group.objects.get(name='common_users'))
нужен тест

2021-09-06 15:37 UTC, UNCLT commented on myAvito/main/tests.py
> +#      Category.objects.get(title='cars'),
Мне нужно было только создать селлера, я не стал особо аккуратничать и закомментил весь файл, кроме листа с данными юзеров и функцией их создания. Совсем забыл про это.

2021-09-06 15:41 UTC, UNCLT commented on myAvito/main/models.py
> +        instance.groups.add(Group.objects.get(name='common_users'))
В файле tests.py или ручной прогон?

2021-09-13 13:56 UTC, morgangt approved these changes

2021-09-30 20:07 UTC, merged